Add weechat, tg, chromium

diff --git a/bin/sync_app b/bin/sync_app
--- a/bin/sync_app
+++ b/bin/sync_app
@@ -102,6 +102,15 @@ app_sync() {
 		shred -n 25 -u -z /tmp/thunderbird-profile.tar.gz
 		mv /tmp/thunderbird-profile.tar.gz.gpg ~/Syncthing/Secured/
 		;;
+	"chromium")
+		[ -d ~/.mozilla ] || (echo "No folder to backup" && exit 1)
+		pgrep chromium > /dev/null && (echo "Shutdown chrome before backup" && exit 1)
+		cd ~ || exit 1
+		tar -czf /tmp/chromium-profile.tar.gz .config/chromium .local/share/applications/chromium-freeworld.desktop bin/chromium-freeworld
+		gpg --passphrase "$password" --yes --batch --output /tmp/chromium-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/chromium-profile.tar.gz
+		shred -n 25 -u -z /tmp/chromium-profile.tar.gz
+		mv /tmp/chromium-profile.tar.gz.gpg ~/Syncthing/Secured/
+		;;
 	"syncthing")
 		[ -d ~/.config/syncthing ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
@@ -109,6 +118,22 @@ app_sync() {
 		gpg --passphrase "$password" --yes --batch --output /tmp/syncthing-profile-$(hostname).tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/syncthing-profile-$(hostname).tar.gz
 		shred -n 25 -u -z /tmp/syncthing-profile-$(hostname).tar.gz
 		mv /tmp/syncthing-profile-$(hostname).tar.gz.gpg ~/Syncthing/Secured/
+		;;
+	"tg")
+		[ -d ~/.config/tg ] || (echo "No folder to backup" && exit 1)
+		cd ~ || exit 1
+		tar --exclude=certificates --exclude=*downloads* --exclude=icons -c -z -f /tmp/tg-profile.tar.gz .config/tg
+		gpg --passphrase "$password" --yes --batch --output /tmp/tg-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/tg-profile.tar.gz
+		shred -n 25 -u -z /tmp/tg-profile.tar.gz
+		mv /tmp/tg-profile.tar.gz.gpg ~/Syncthing/Secured/
+		;;
+	"weechat")
+		[ -d ~/.weechat ] || (echo "No folder to backup" && exit 1)
+		cd ~ || exit 1
+		tar -c -z -f /tmp/weechat-profile.tar.gz .weechat
+		gpg --passphrase "$password" --yes --batch --output /tmp/weechat-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/weechat-profile.tar.gz
+		shred -n 25 -u -z /tmp/weechat-profile.tar.gz
+		mv /tmp/weechat-profile.tar.gz.gpg ~/Syncthing/Secured/
 		;;
 	esac
 }
@@ -182,6 +207,16 @@ app_restore() {
 		tar -xzf /tmp/firefox-profile.tar.gz -C ~/
 		shred -n 25 -u -z /tmp/firefox-profile.tar.gz
 		;;
+	"chromium")
+		gpg --output /tmp/chromium-profile.tar.gz --decrypt ~/Syncthing/Secured/chromium-profile.tar.gz.gpg
+		if [ ! -f /tmp/chromium-profile.tar.gz ]; then
+			echo "Failed to decrypt"
+			exit 1
+		fi
+		rm -rf ~/.config/chromium
+		tar -xzf /tmp/chromium-profile.tar.gz -C ~/
+		shred -n 25 -u -z /tmp/chromium-profile.tar.gz
+		;;
 	"thunderbird")
 		gpg --output /tmp/thunderbird-profile.tar.gz --decrypt ~/Syncthing/Secured/thunderbird-profile.tar.gz.gpg
 		if [ ! -f /tmp/thunderbird-profile.tar.gz ]; then
@@ -203,6 +238,24 @@ app_restore() {
 		tar -xzf /tmp/syncthing-profile-$(hostname).tar.gz -C ~/
 		shred -n 25 -u -z /tmp/syncthing-profile-$(hostname).tar.gz
 		systemctl restart --user syncthing
+		;;
+	"tg")
+		gpg --output /tmp/tg-profile.tar.gz --decrypt ~/Syncthing/Secured/tg-profile.tar.gz.gpg
+		if [ ! -f /tmp/tg-profile.tar.gz ]; then
+			echo "Failed to decrypt"
+			exit 1
+		fi
+		tar -xzf /tmp/tg-profile.tar.gz -C ~/
+		shred -n 25 -u -z /tmp/tg-profile.tar.gz
+		;;
+	"weechat")
+		gpg --output /tmp/weechat-profile.tar.gz --decrypt ~/Syncthing/Secured/weechat-profile.tar.gz.gpg
+		if [ ! -f /tmp/weechat-profile.tar.gz ]; then
+			echo "Failed to decrypt"
+			exit 1
+		fi
+		tar -xzf /tmp/weechat-profile.tar.gz -C ~/
+		shred -n 25 -u -z /tmp/weechat-profile.tar.gz
 		;;
 	esac
 }
