sync: add claws-mail support

diff --git a/bin/sync_app b/bin/sync_app
--- a/bin/sync_app
+++ b/bin/sync_app
@@ -11,7 +11,7 @@ app_sync() {
 	"gpg")
 		[ -d ~/.gnupg ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar cfv - .gnupg | xz -T 0 -9e >/tmp/gnupg-keys.tar.xz
+		tar cf - .gnupg | xz -T 0 -9e >/tmp/gnupg-keys.tar.xz
 		gpg --output /tmp/gnupg-keys.tar.xz.gpg --symmetric /tmp/gnupg-keys.tar.xz
 		shred -n 25 -u -z /tmp/gnupg-keys.tar.xz
 		mv /tmp/gnupg-keys.tar.xz.gpg ~/Syncthing/Secured/
@@ -19,7 +19,7 @@ app_sync() {
 	"pass")
 		[ -d ~/.password-store ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar cfv - .password-store | xz -T 0 -9e >/tmp/pass-store.tar.xz
+		tar cf - .password-store | xz -T 0 -9e >/tmp/pass-store.tar.xz
 		gpg --output /tmp/pass-store.tar.xz.gpg --symmetric /tmp/pass-store.tar.xz
 		shred -n 25 -u -z /tmp/pass-store.tar.xz
 		mv /tmp/pass-store.tar.xz.gpg ~/Syncthing/Secured/
@@ -27,13 +27,13 @@ app_sync() {
 	"xfce4")
 		[ -d ~/.config/xfce4 ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar cfv - .config/xfce4/ .config/Thunar | xz -T 0 -9e >~/dotfiles/xfce/xfce4-setup.tar.xz
+		tar cf - .config/xfce4/ .config/Thunar | xz -T 0 -9e >~/dotfiles/xfce/xfce4-setup.tar.xz
 		git -C ~/dotfiles commit -m "xfce4: update settings" xfce/xfce4-setup.tar.xz
 		;;
 	"pidgin")
 		[ -d ~/.purple ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar --exclude=*downloads* --exclude=.git -c -v -f - .purple | xz -T 0 -9e>/tmp/pidgin-profile.tar.xz
+		tar --exclude=*downloads* --exclude=.git --exclude=icons --exclude=logs -c -f - .purple | xz -T 0 -9e>/tmp/pidgin-profile.tar.xz
 		gpg --output /tmp/pidgin-profile.tar.xz.gpg --symmetric /tmp/pidgin-profile.tar.xz
 		shred -n 25 -u -z /tmp/pidgin-profile.tar.xz
 		mv /tmp/pidgin-profile.tar.xz.gpg ~/Syncthing/Secured/
@@ -43,7 +43,7 @@ app_sync() {
 		find ~/.mozilla/ -iname "*cache*" | xargs rm -rf
 		find .mozilla/firefox/*/storage/default/http* -iname "*.files" | xargs rm -rf
 		cd ~ || exit 1
-		tar cfv - .mozilla | xz -T 0 -9e >/tmp/firefox-profile.tar.xz
+		tar cf - .mozilla | xz -T 0 -9e >/tmp/firefox-profile.tar.xz
 		gpg --output /tmp/firefox-profile.tar.xz.gpg --symmetric /tmp/firefox-profile.tar.xz
 		shred -n 25 -u -z /tmp/firefox-profile.tar.xz
 		mv /tmp/firefox-profile.tar.xz.gpg ~/Syncthing/Secured/
@@ -51,7 +51,7 @@ app_sync() {
 	"chromium")
 		[ -d ~/.config/chromium ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar cfv - .config/chromium | xz -T 0 -9e >/tmp/chromium-profile.tar.xz
+		tar cf - .config/chromium | xz -T 0 -9e >/tmp/chromium-profile.tar.xz
 		gpg --output /tmp/chromium-profile.tar.xz.gpg --symmetric /tmp/chromium-profile.tar.xz
 		shred -n 25 -u -z /tmp/chromium-profile.tar.xz
 		mv /tmp/chromium-profile.tar.xz.gpg ~/Syncthing/Secured/
@@ -60,7 +60,7 @@ app_sync() {
 		[ -d ~/.thunderbird ] || (echo "No folder to backup" && exit 1)
 		find ~/.thunderbird/ -iname "*cache*" | xargs rm -rf
 		cd ~ || exit 1
-		tar cfv - --exclude=.thunderbird/*-default/ImapMail .thunderbird/ | xz -T 0 -9e >/tmp/thunderbird-profile.tar.xz
+		tar cf - --exclude=.thunderbird/*/extensions/lang* --exclude=.thunderbird/*-default/ImapMail .thunderbird/ | xz -T 0 -9e >/tmp/thunderbird-profile.tar.xz
 		gpg --output /tmp/thunderbird-profile.tar.xz.gpg --symmetric /tmp/thunderbird-profile.tar.xz
 		shred -n 25 -u -z /tmp/thunderbird-profile.tar.xz
 		mv /tmp/thunderbird-profile.tar.xz.gpg ~/Syncthing/Secured/
@@ -68,7 +68,7 @@ app_sync() {
 	"sylpheed")
 		[ -d ~/.sylpheed-2.0 ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar cfv - .sylpheed-2.0/ | xz -T 0 -9e >/tmp/sylpheed-profile.tar.xz
+		tar cf - .sylpheed-2.0/ | xz -T 0 -9e >/tmp/sylpheed-profile.tar.xz
 		gpg --output /tmp/sylpheed-profile.tar.xz.gpg --symmetric /tmp/sylpheed-profile.tar.xz
 		shred -n 25 -u -z /tmp/sylpheed-profile.tar.xz
 		mv /tmp/sylpheed-profile.tar.xz.gpg ~/Syncthing/Secured/
@@ -76,10 +76,18 @@ app_sync() {
 	"geary")
 		[ -d ~/.config/geary ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
-		tar cfv - .config/geary/ | xz -T 0 -9e >/tmp/geary-profile.tar.xz
+		tar cf - .config/geary/ | xz -T 0 -9e >/tmp/geary-profile.tar.xz
 		gpg --output /tmp/geary-profile.tar.xz.gpg --symmetric /tmp/geary-profile.tar.xz
 		shred -n 25 -u -z /tmp/geary-profile.tar.xz
 		mv /tmp/geary-profile.tar.xz.gpg ~/Syncthing/Secured/
+		;;
+	"claws-mail")
+		[ -d ~/.claws-mail ] || (echo "No folder to backup" && exit 1)
+		cd ~ || exit 1
+		tar cf - --exclude=imapcache --exclude=*.bak .claws-mail | xz -T 0 -9e >/tmp/claws-profile.tar.xz
+		gpg --output /tmp/claws-profile.tar.xz.gpg --symmetric /tmp/claws-profile.tar.xz
+		shred -n 25 -u -z /tmp/claws-profile.tar.xz
+		mv /tmp/claws-profile.tar.xz.gpg ~/Syncthing/Secured/
 		;;
 	esac
 }
@@ -172,6 +180,16 @@ app_restore() {
 		rm -rf ~/.sylpheed-2.0
 		xz -T 0 -dc /tmp/sylpheed-profile.tar.xz | tar x -C ~/
 		shred -n 25 -u -z /tmp/sylpheed-profile.tar.xz
+		;;
+	"claws-mail")
+		gpg --output /tmp/claws-profile.tar.xz --decrypt ~/Syncthing/Secured/claws-profile.tar.xz.gpg
+		if [ ! -f /tmp/claws-profile.tar.xz ]; then
+			echo "Failed to decrypt"
+			exit 1
+		fi
+		rm -rf ~/.claws-mail
+		xz -T 0 -dc /tmp/claws-profile.tar.xz | tar x -C ~/
+		shred -n 25 -u -z /tmp/claws-profile.tar.xz
 		;;
 	"geary")
 		gpg --output /tmp/geary-profile.tar.xz --decrypt ~/Syncthing/Secured/geary-profile.tar.xz.gpg
