Sync: switch from gpg to openssl

diff --git a/bin/.local/bin/sync_app b/bin/.local/bin/sync_app
--- a/bin/.local/bin/sync_app
+++ b/bin/.local/bin/sync_app
@@ -35,23 +35,9 @@ app_sync() {
 		[ -d ~/.ssh ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
 		tar -czf /tmp/ssh-keys.tar.gz .ssh
-		gpg --passphrase "$password" --yes --batch --output /tmp/ssh-keys.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/ssh-keys.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/ssh-keys.tar.gz -out /tmp/ssh-keys.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/ssh-keys.tar.gz
-		cp /tmp/ssh-keys.tar.gz.gpg ~/Syncthing/Secured/
-		;;
-	"gpg")
-		[ -d ~/.gnupg ] || (echo "No folder to backup" && exit 1)
-		cd ~ || exit 1
-		tar -czf /tmp/gnupg-keys.tar.gz .gnupg
-		gpg --passphrase "$password" --yes --batch --output /tmp/gnupg-keys.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/gnupg-keys.tar.gz
-		shred -n 25 -u -z /tmp/gnupg-keys.tar.gz
-		cp /tmp/gnupg-keys.tar.gz.gpg ~/Syncthing/Secured/
-		;;
-	"xfce4")
-		[ -d ~/.config/xfce4 ] || (echo "No folder to backup" && exit 1)
-		cd ~ || exit 1
-		tar -czf ~/dotfiles/_desktop/xfce4-setup.tar.gz .config/xfce4/ .config/Thunar .local/share/themes
-		git -C ~/dotfiles commit -m "xfce4: update settings" _desktop/xfce4-setup.tar.gz
+		cp /tmp/ssh-keys.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"gnome")
 		mkdir /tmp/bkp
@@ -59,75 +45,77 @@ app_sync() {
 		for f in ${GNOME_BACKUP[@]}; do
 			dconf dump /org/gnome/$f/ >org.gnome.$f.conf
 		done
-		tar -czf ~/dotfiles/_desktop/gnome-setup.tar.gz /tmp/bkp "$HOME"/.local/share/gnome-shell/extensions/
+		tar -czf ~/dotfiles/_desktop/gnome-setup.tar.gz /tmp/bkp # "$HOME"/.local/share/gnome-shell/extensions/
 		rm -rf /tmp/bkp
 		git -C ~/dotfiles commit -m "gnome: update settings" _desktop/gnome-setup.tar.gz
-		;;
-	"pidgin")
-		[ -d ~/.purple ] || (echo "No folder to backup" && exit 1)
-		cd ~ || exit 1
-		tar --exclude=certificates --exclude=gowhatsapp --exclude=*photos* --exclude=*documents* --exclude=*voice* --exclude=*videos* --exclude=*animations* --exclude=*downloads* --exclude=icons -c -z -f /tmp/pidgin-profile.tar.gz .purple
-		gpg --passphrase "$password" --yes --batch --output /tmp/pidgin-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/pidgin-profile.tar.gz
-		shred -n 25 -u -z /tmp/pidgin-profile.tar.gz
-		mv /tmp/pidgin-profile.tar.gz.gpg ~/Syncthing/Secured/
 		;;
 	"firefox")
 		[ -d ~/.mozilla ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
 		find .mozilla -type d -iname "*cache*" | xargs rm -rf
 		tar -c -z -f /tmp/firefox-profile.tar.gz --exclude="*cache*" --exclude=".mozilla/firefox/*/storage/default/http*" .mozilla
-		gpg --passphrase "$password" --yes --batch --output /tmp/firefox-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/firefox-profile.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/firefox-profile.tar.gz -out /tmp/firefox-profile.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/firefox-profile.tar.gz
-		mv /tmp/firefox-profile.tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/firefox-profile.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"thunderbird")
 		[ -d ~/.thunderbird ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
 		tar -c -z -f /tmp/thunderbird-profile.tar.gz --exclude="*cache*" --exclude=.thunderbird/*/extensions/lang* --exclude=.thunderbird/*-default/ImapMail .thunderbird/
-		gpg --passphrase "$password" --yes --batch --output /tmp/thunderbird-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/thunderbird-profile.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/thunderbird-profile.tar.gz -out /tmp/thunderbird-profile.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/thunderbird-profile.tar.gz
-		mv /tmp/thunderbird-profile.tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/thunderbird-profile.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"chromium")
 		[ -d ~/.config/chromium ] || (echo "No folder to backup" && exit 1)
 		# pgrep chromium > /dev/null && (echo "Shutdown chrome before backup" && exit 1)
 		cd ~ || exit 1
 		tar --exclude=*Cache* -czf /tmp/chromium-profile.tar.gz .config/chromium .local/share/applications/chromium-freeworld.desktop bin/chromium-freeworld
-		gpg --passphrase "$password" --yes --batch --output /tmp/chromium-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/chromium-profile.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/chromium-profile.tar.gz -out /tmp/chromium-profile.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/chromium-profile.tar.gz
-		mv /tmp/chromium-profile.tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/chromium-profile.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"syncthing")
 		[ -d ~/.config/syncthing ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
 		tar -czf /tmp/syncthing-profile-$(hostname).tar.gz .config/syncthing/
-		gpg --passphrase "$password" --yes --batch --output /tmp/syncthing-profile-$(hostname).tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/syncthing-profile-$(hostname).tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/syncthing-profile-$(hostname).tar.gz -out /tmp/syncthing-profile-$(hostname).tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/syncthing-profile-$(hostname).tar.gz
-		mv /tmp/syncthing-profile-$(hostname).tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/syncthing-profile-$(hostname).tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"tg")
 		[ -d ~/.config/tg ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
 		tar --exclude=files -c -z -f /tmp/tg-profile.tar.gz .config/tg .cache/tg
-		gpg --passphrase "$password" --yes --batch --output /tmp/tg-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/tg-profile.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/tg-profile.tar.gz -out /tmp/tg-profile.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/tg-profile.tar.gz
-		mv /tmp/tg-profile.tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/tg-profile.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"weechat")
 		[ -d ~/.weechat ] || (echo "No folder to backup" && exit 1)
 		cd ~ || exit 1
 		tar -c -z -f /tmp/weechat-profile.tar.gz .weechat
-		gpg --passphrase "$password" --yes --batch --output /tmp/weechat-profile.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/weechat-profile.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/weechat-profile.tar.gz -out /tmp/weechat-profile.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/weechat-profile.tar.gz
-		mv /tmp/weechat-profile.tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/weechat-profile.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	"flatpak")
 		[ -d ~/.var/app ] || (echo "No folder to backup" && exit 1)
 		cd ~/.var || exit 1
 		tar --exclude=*cache* -c -z -f /tmp/flatpak-data.tar.gz app
-		gpg --passphrase "$password" --yes --batch --output /tmp/flatpak-data.tar.gz.gpg --symmetric --cipher-algo AES256 /tmp/flatpak-data.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/flatpak-data.tar.gz -out /tmp/flatpak-data.tar.gz.enc -k "$password"
 		shred -n 25 -u -z /tmp/flatpak-data.tar.gz
-		mv /tmp/flatpak-data.tar.gz.gpg ~/Syncthing/Secured/
+		mv /tmp/flatpak-data.tar.gz.enc ~/Syncthing/Secured/
+		;;
+	"connections")
+		[ -d /etc/NetworkManager/system-connections/ ] || (echo "No folder to backup" && exit 1)
+		[ -d /var/lib/bluetooth/ ] || (echo "No folder to backup" && exit 1)
+		cd / || exit 1
+		sudo tar -c -z -f /tmp/system-connections.tar.gz /etc/NetworkManager/system-connections/ /var/lib/bluetooth/
+		sudo chown $USER. /tmp/system-connections.tar.gz
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in /tmp/system-connections.tar.gz -out /tmp/system-connections.tar.gz.enc -k "$password"
+		sudo shred -n 25 -u -z /tmp/system-connections.tar.gz
+		mv /tmp/system-connections.tar.gz.enc ~/Syncthing/Secured/
 		;;
 	esac
 }
@@ -137,39 +125,13 @@ app_restore() {
 	TARGET=$1
 	case "$TARGET" in
 	"ssh")
-		gpg --output /tmp/ssh-keys.tar.gz --decrypt ~/Syncthing/Secured/ssh-keys.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/ssh-keys.tar.gz.enc -out /tmp/ssh-keys.tar.gz
 		if [ ! -f /tmp/ssh-keys.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
 		fi
 		tar -xzf /tmp/ssh-keys.tar.gz -C ~/
 		shred -n 25 -u -z /tmp/ssh-keys.tar.gz
-		;;
-	"gpg")
-		gpg --output /tmp/gnupg-keys.tar.gz --decrypt ~/Syncthing/Secured/gnupg-keys.tar.gz.gpg
-		if [ ! -f /tmp/gnupg-keys.tar.gz ]; then
-			echo "Failed to decrypt"
-			exit 1
-		fi
-		rm -rf ~/.gnupg
-		tar -xzf /tmp/gnupg-keys.tar.gz -C ~/
-		shred -n 25 -u -z /tmp/gnupg-keys.tar.gz
-		;;
-	"xfce4")
-		rm -rf ~/.config/xfce4 ~/.config/Thunar ~/.config/Mousepad
-		tar -xzf ~/dotfiles/_desktop/xfce4-setup.tar.gz -C ~/
-		killall -9 xfconfd || true
-		killall -9 xfce4-panel || true
-		killall -9 thunar || true
-		killall -9 xfce4-volumed-pulse || true
-		killall -9 xfdesktop || true
-		killall -9 xfce4-power-manager || true
-		killall -9 xfce4-notifyd || true
-		nohup xfce4-power-manager &
-		nohup xfce4-panel &
-		nohup /usr/lib64/xfce4/notifyd/xfce4-notifyd &
-		nohup xfce4-volumed-pulse &
-		nohup xfwm4 --replace &
 		;;
 	"gnome")
 		rm -rf /tmp/bkp "$HOME"/.local/share/gnome-shell/extensions/
@@ -181,17 +143,8 @@ app_restore() {
 		done
 		rm -rf /tmp/bkp
 		;;
-	"pidgin")
-		gpg --output /tmp/pidgin-profile.tar.gz --decrypt ~/Syncthing/Secured/pidgin-profile.tar.gz.gpg
-		if [ ! -f /tmp/pidgin-profile.tar.gz ]; then
-			echo "Failed to decrypt"
-			exit 1
-		fi
-		tar -xzf /tmp/pidgin-profile.tar.gz -C ~/
-		shred -n 25 -u -z /tmp/pidgin-profile.tar.gz
-		;;
 	"firefox")
-		gpg --output /tmp/firefox-profile.tar.gz --decrypt ~/Syncthing/Secured/firefox-profile.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/firefox-profile.tar.gz.enc -out /tmp/firefox-profile.tar.gz
 		if [ ! -f /tmp/firefox-profile.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -201,7 +154,7 @@ app_restore() {
 		shred -n 25 -u -z /tmp/firefox-profile.tar.gz
 		;;
 	"chromium")
-		gpg --output /tmp/chromium-profile.tar.gz --decrypt ~/Syncthing/Secured/chromium-profile.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/chromium-profile.tar.gz.enc -out /tmp/chromium-profile.tar.gz
 		if [ ! -f /tmp/chromium-profile.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -211,7 +164,7 @@ app_restore() {
 		shred -n 25 -u -z /tmp/chromium-profile.tar.gz
 		;;
 	"thunderbird")
-		gpg --output /tmp/thunderbird-profile.tar.gz --decrypt ~/Syncthing/Secured/thunderbird-profile.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/thunderbird-profile.tar.gz.enc -out /tmp/thunderbird-profile.tar.gz
 		if [ ! -f /tmp/thunderbird-profile.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -222,7 +175,7 @@ app_restore() {
 		;;
 	"syncthing")
 		systemctl stop --user syncthing
-		gpg --output /tmp/syncthing-profile-$(hostname).tar.gz --decrypt ~/Syncthing/Secured/syncthing-profile-$(hostname).tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/syncthing-profile-$(hostname).tar.gz.enc -out /tmp/syncthing-profile-$(hostname).tar.gz
 		if [ ! -f /tmp/syncthing-profile-$(hostname).tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -233,7 +186,7 @@ app_restore() {
 		systemctl restart --user syncthing
 		;;
 	"tg")
-		gpg --output /tmp/tg-profile.tar.gz --decrypt ~/Syncthing/Secured/tg-profile.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/tg-profile.tar.gz.enc -out /tmp/tg-profile.tar.gz
 		if [ ! -f /tmp/tg-profile.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -242,7 +195,7 @@ app_restore() {
 		shred -n 25 -u -z /tmp/tg-profile.tar.gz
 		;;
 	"weechat")
-		gpg --output /tmp/weechat-profile.tar.gz --decrypt ~/Syncthing/Secured/weechat-profile.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/weechat-profile.tar.gz.enc -out /tmp/weechat-profile.tar.gz
 		if [ ! -f /tmp/weechat-profile.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -251,7 +204,7 @@ app_restore() {
 		shred -n 25 -u -z /tmp/weechat-profile.tar.gz
 		;;
 	"flatpak")
-		gpg --output /tmp/flatpak-data.tar.gz --decrypt ~/Syncthing/Secured/flatpak-data.tar.gz.gpg
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/flatpak-data.tar.gz.enc -out /tmp/flatpak-data.tar.gz
 		if [ ! -f /tmp/flatpak-data.tar.gz ]; then
 			echo "Failed to decrypt"
 			exit 1
@@ -259,6 +212,16 @@ app_restore() {
 		rm -rf ~/.var/app
 		tar -xzf /tmp/flatpak-data.tar.gz -C ~/.var/
 		shred -n 25 -u -z /tmp/flatpak-data.tar.gz
+		;;
+	"connections")
+		openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -d -in ~/Syncthing/Secured/system-connections.tar.gz.enc -out /tmp/system-connections.tar.gz
+		if [ ! -f /tmp/system-connections.tar.gz ]; then
+			echo "Failed to decrypt"
+			exit 1
+		fi
+		sudo tar -xzf /tmp/system-connections.tar.gz -C /
+		shred -n 25 -u -z /tmp/system-connections.tar.gz
+		sudo systemctl restart NetworkManager
 		;;
 	esac
 }
